---

- name: Install required packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ shutdown_if_battery_low__base_packages }}'
    - '{{ shutdown_if_battery_low__packages }}'

- name: Copy script to target
  copy:
    src: 'shutdown_if_battery_low.sh'
    dest: '{{ shutdown_if_battery_low__script_filepath }}'
    mode: 0755
    owner: root
    group: root
  notify: [ 'Restart shutdown_if_battery_low' ]

- name: Create systemd environment file
  template:
    src: 'etc/default/shutdown_if_battery_low.j2'
    dest: '{{ shutdown_if_battery_low__environment_filepath }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart shutdown_if_battery_low' ]

- name: Create systemd service file
  template:
    src: 'etc/systemd/system/shutdown_if_battery_low.service.j2'
    dest: '/etc/systemd/system/shutdown_if_battery_low.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Reload systemd', 'Restart shutdown_if_battery_low' ]

- name: Enable shutdown_if_battery_low
  systemd:
    name: 'shutdown_if_battery_low.service'
    state: 'started'
    enabled: True
